### ISSUE TITLE
Mention `foo.bar = ` syntax for attrsets

### ISSUE THREAD

**Issue by tejing1** [divnix/nix-book#14]
https://book.divnix.com/ch05-01-language-basics.html#attribute-set-attr-set should probably mention that you can set keys in nested attrsets with `foo.bar = `, and that you can set multiple keys under the same top-level key with multiple lines, not necessarily grouped together:
```nix
{
  foo.bar = 1;
  quux = 2;
  foo.baz = 3;
}
```

The fact that this also works for `let`s... we can probably skip. :-P

**Comment by jonringer** [comment]
oh yea, how did I forget this... lol
