### ISSUE TITLE
Great Book

### ISSUE THREAD

**Issue by mahyarmirrashed** [divnix/nix-book#29]
This was the first book I read where I felt like I understood Nix.

I noticed that a lot of section 4 is still TODO. Is this book complete? Should it be marked as archived?

Thanks for your work 🙏

**Comment by jonringer** [comment]
We are likely to move this to github.com/ekala-project, and finishing the content. I took a 18month hiatus and some other stuff demotivated me from completing it.

> Thanks for your work 🙏

Thank you :)

**Comment by mahyarmirrashed** [comment]
I'm interested in the Ekala project. Do you have a Discord server for it? I would like to learn more.

**Comment by jonringer** [comment]
Yea, https://discord.gg/JG6zmPTutq
