### ISSUE TITLE
Caching should be mentioned before readers get the wrong impression

### ISSUE THREAD

**Issue by tejing1** [divnix/nix-book#8]
At this point:
https://github.com/divnix/nix-book/blob/f6448f447d5584854803ac7829e3dd1c00686a32/src/ch02-00-introduction.md?plain=1#L61-L62
A new reader might get the mistaken impression that nix expects everyone to build packages locally. Some mention of the fact that complete builds can be fetched from a cache would be nice.

**Comment by jonringer** [comment]
Agreed, don't want to spook people who have tried Gentoo :)
